Description: This template deploys a CodeBuild project to build a container image

Parameters:
  CodeBuildProjectName:
    Type: String
  CodeBuildServiceRoleName:
    Type: String

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "CodeBuild Settings"
        Parameters: 
          - CodeBuildProjectName
          - CodeBuildServiceRoleName
    ParameterLabels: 
      CodeBuildProjectName: 
        default: "What is the CodeBuild Project Name for Container images build?"
      CodeBuildServiceRoleName: 
        default: "Which CodeBuild service role should be used?"

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildProjectName
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec_containerImage.yml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0-1.7.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: CONTAINER_NAME
          Value: ''
        - Name: ECR_REPOSITORY_URI
          Value: ''
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/${CodeBuildServiceRoleName}

